"""Regression snapshots for the three final manuscript tables.

These tests intentionally check the display CSVs generated by the pipeline rather
than Word formatting. They protect the manuscript-facing rounding, ordering and
labels that were locked during revision.
"""
from pathlib import Path
import pandas as pd

from measles_analysis.pipeline import run_pipeline

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "derived"


def test_table1_locked_national_row(generated_outputs):
    out, _ = generated_outputs
    t1 = pd.read_csv(out / "table1_manuscript.csv", dtype=str)
    row = t1.iloc[0].to_dict()
    assert row["Province"] == "NATIONAL / aggregate"
    assert row["MCV1 coverage % (95% CI)"] == "51.2 (49.1-53.2)"
    assert row["Rcov (95% CI)"] == "7.95 (7.69-8.20)"
    assert row["3.5-yr upper-bound unprotected"] == "3,020,600"
    assert row["Preferential children needing SIA"] == "4,056,042"
    assert row["Random children needing SIA"] == "7,530,648"
    assert row["Preferential reach category / robust"] == "40–<60% / Yes"


def test_table2_final_six_order_and_values(generated_outputs):
    out, _ = generated_outputs
    t2 = pd.read_csv(out / "table2_manuscript.csv", dtype=str)
    assert t2["Province"].tolist() == ["Uruzgan", "Paktika", "Helmand", "Kabul", "Herat", "Bamyan"]
    assert t2["Deterministic peak I"].tolist() == ["26,490", "17,093", "87,849", "62,227", "18,190", "1,012"]
    assert t2["Establishment probability (%)"].tolist() == ["93.9%", "91.8%", "91.4%", "83.2%", "77.3%", "65.9%"]


def test_table3_final_order(generated_outputs):
    out, _ = generated_outputs
    t3 = pd.read_csv(out / "table3_manuscript.csv", dtype=str)
    assert t3["Province"].tolist() == [
        "Uruzgan", "Paktika", "Nuristan", "Helmand", "Nimroz", "Panjshir", "Kabul", "Herat", "Bamyan"
    ]
